config/routes.rb
# encoding: utf-8
#
# Redmine plugin for quick attribute setting of redmine issues
#
# Copyright © 2018 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do

  # resource quickies creation and administration
  resources :projects do #project
    member do #project_names
      scope 'settings' do #only for settings
        resources :attribute_quickies, :param => :attribute_quicky_id, :except => :show #all necessary routes
      end
    end
  end

  # additional link for resource quickies creation and administration
  match '/projects/:id/settings/attribute_quickies/preview/notes' => 'attribute_quickies#issue', :as => 'preview_attribute_quickies_notes', :via => [:get]

  # link to retrieve last issue changes
  match '/projects/:id/settings/attribute_quickies/issue/attributes' => 'attribute_quickies#issue_attributes', :as => 'attribute_quickies_issue_attributes', :via => [:put]
  
end

app/models/attribute_quicky.rb
# encoding: utf-8
#
# Redmine plugin for quick attribute setting of redmine issues
#
# Copyright © 2018 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class AttributeQuicky < ActiveRecord::Base

  unloadable

  include Redmine::SafeAttributes
  
  acts_as_positioned
  acts_as_attachable 
  
  validates_presence_of :name
  validates_presence_of :description

  attr_protected   :id

  serialize        :attribute_list
  serialize		   :time_entry
  
  safe_attributes  'name',					
				   'description',			
				#  'project_id',				
				   'attribute_list',			
				   'attribute_list_action',	
				   'issue_description_action',
				   'add_notes',				
				   'notes',					
				   'private_notes',			
				   'assign_to_last_author',	
				   'issue_id',				
				   'issue_template_id',       
				   'is_for_all',				
				   'visibility',				
				   'position',
				   'time_entry'
  
  belongs_to :issue
  belongs_to :project
  has_and_belongs_to_many :roles,    :join_table => "#{table_name_prefix}attribute_quickies_roles#{table_name_suffix}",    :foreign_key => "attribute_quicky_id"
  has_and_belongs_to_many :trackers, :join_table => "#{table_name_prefix}attribute_quickies_trackers#{table_name_suffix}", :foreign_key => "attribute_quicky_id"
  
  scope :visible, lambda {|*args|
    user = args.shift || User.current
    if user.admin?
      # nop
    elsif user.memberships.any?
      where("#{table_name}.visibility = ?" + 
        " OR #{table_name}.id IN (SELECT DISTINCT aqr.attribute_quicky_id FROM #{Member.table_name} m" +
        " INNER JOIN #{MemberRole.table_name} mr ON mr.member_id = m.id" +
        " INNER JOIN #{table_name_prefix}attribute_quickies_roles#{table_name_suffix} aqr ON aqr.role_id = mr.role_id" +
        " WHERE m.user_id = ?)",
        true, user.id)
    else
      where(:visibility => true)
    end
  }

  # ------------------------------------------------------------------------------------ #
  def <=>(attribute_quicky)
    position <=> attribute_quicky.position
  end

  # ------------------------------------------------------------------------------------ #
  def to_s 
    name 
  end
  
private

end #class

app/controllers/attribute_quickies_controller.rb
# encoding: utf-8
#
# Redmine plugin for quick attribute setting of redmine issues
#
# Copyright © 2018 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class AttributeQuickiesController < ApplicationController

  unloadable

  before_filter :find_project #filter is part of redmine
  before_filter :authorize # filter is part of redmine
  before_filter :find_attribute_quicky, :only => [:show, :update, :edit ]
  before_filter :build_new_attribute_quicky_from_params, :only => [:new, :create, :issue, :issue_attributes]
  
  helper :issues 
  helper :custom_fields 
  helper :attachments 
  helper :timelog

  # ------------------------------------------------------------------------------------ #
  def index
    @attribute_quickies = AttributeQuicky.where(:project_id => @project.id).order(:position).to_a
  end #def

  # ------------------------------------------------------------------------------------ #
  def show
    edit
    render :action => 'edit'
  end #def
  
  # ------------------------------------------------------------------------------------ #
  def new
    # before filter: build_new_attribute_quicky_from_params
  end #def
  
  # ------------------------------------------------------------------------------------ #
  def create
	# this is a call from an objected (first time) edit (or new) form
	
    @attribute_quicky.save_attachments(params[:attachments])
        
	if @attribute_quicky.save	
 	  flash[:notice] = l(:attribute_quickies_notice_successful_create)
	  render :action => 'edit', :attribute_quicky => params[:attribute_quicky]
	else
	  flash[:error] = l(:attribute_quickies_notice_erroneus_create)
	  render :action => 'new', :attribute_quicky => params[:attribute_quicky]
	end
	
     flash.discard
	 return
	
  end #def
  
  # ------------------------------------------------------------------------------------ #
  def edit
    # before_filter: find_attribute_quicky
    # do not compile attribute list, keep original copy
    @issue = @attribute_quicky.presence && @attribute_quicky.issue
     new_issue unless @issue.present?
    @attribute_quicky.issue_id = nil if @issue.blank? || !@issue.visible?    
    @journal_details = @attribute_quicky.attribute_list.presence && @attribute_quicky.attribute_list.map {|attr| JournalDetail.instantiate(attr) }
    @journal_details ||= []
    @notes = @attribute_quicky.notes
    @attribute_quicky.issue_template_id = nil #unset to prevent overiding formerly copied attributes at next save action
    @time_entry = TimeEntry.new(@attribute_quicky.time_entry)
     
  end #def
  
  # ------------------------------------------------------------------------------------ #
  def update
    #before_filter: find_attribute_quicky
    
    if request.format.to_s =~ /text\/html/ 
      # this is a call from a user edited form

      @issue = Issue.where(:id => params[:attribute_quicky][:issue_template_id].to_i).first if params[:attribute_quicky].present? && params[:attribute_quicky][:issue_template_id].present?
       params[:attribute_quicky].except!(:issue_template_id) if @issue.blank? && params[:attribute_quicky].present? && params[:attribute_quicky][:issue_template_id].present?
       new_issue if @issue.blank?
       new_issue if !@issue.visible?(User.current)
	  @attribute_quicky.update_attributes( params[:attribute_quicky] )
      
      if !@issue.new_record? #we have a real new input
        @attribute_quicky.issue = @issue
	      compile_attribute_list
	    @attribute_quicky.attribute_list = @attribute_list  	    
	  else
	    @attribute_list = @attribute_quicky.attribute_list
	  end
	  
	  @journal_details = @attribute_list.map {|attr| JournalDetail.instantiate(attr) }
	  @notes = @attribute_quicky.notes
	  
	  @attribute_quicky.save_attachments(params[:attachments])

	  new_time_entry
	  if params.key?(:time_entry)
	    @time_entry.safe_attributes = params[:time_entry]
	    @attribute_quicky.time_entry = params[:time_entry]
	  else
	     @attribute_quicky.time_entry = {}
	  end

	  if @attribute_quicky.save	
		feedback = l(:attribute_quickies_notice_successful_update, :id => @attribute_quicky.id )
		flash[:notice] = feedback
	  else
		feedback = l(:attribute_quickies_notice_erroneus_update, :id => @attribute_quicky.id )
		flash[:error] = feedback
	  end

    else 
	  #this is a call from javascript to reposition item in list
	  if params.key?(:attribute_quicky) && params[:attribute_quicky].key?(:position)
	    @attribute_quicky.position = params[:attribute_quicky][:position]
	    @attribute_quicky.save #if this did not work - just ignore
	  end
    end
     
    respond_to do |format|
	
	  format.html { render :action => 'edit', :attribute_quicky => params[:attribute_quicky]
					flash.discard
				  }
				  
	  format.js   { render :nothing => true 
	              } # for positioning with javascript
    end

  end #def
  
  # ------------------------------------------------------------------------------------ #
  def destroy
    AttributeQuicky.find(params[:attribute_quicky_id]).destroy
    redirect_to :controller => 'projects', 
    			:action => 'settings', 
    			:id => @project, 
	  			:tab => 'attribute_quickies'
  rescue
    flash[:error] = l(:attribute_quickies_notice_delete_error, :id => @attribute_quicky.id )
    redirect_to :controller => 'projects', 
    			:action => 'settings', 
    			:id => @project, 
	  			:tab => 'attribute_quickies'
  end #def
  
  # ------------------------------------------------------------------------------------ #
  def issue
   
    @attachments = []

    render :layout => false

  end #def

  # ------------------------------------------------------------------------------------ #
  def issue_attributes

    @journal_details = []
    @content = ""
    if params[:attribute_quicky].present? && params[:attribute_quicky][:issue_template_id].present?
      @issue = Issue.where(:id=>params[:attribute_quicky][:issue_template_id]).first
      @attribute_list =  (@issue.present? && @issue.visible?(User.current)) ? issue_attribute_list( @issue ) : []
      @journal_details = @attribute_list.map {|attr| JournalDetail.instantiate(attr) }
      @notes = params[:attribute_quicky][:notes]
      @content = render_to_string :partial => 'issue_attributes_form'
      if @issue.present?
        @hook_content = render_to_string :partial => 'issue_attributes_form_hook'
      else
        @hook_content = ""
      end

	  respond_to do |format|
		format.js { }
	  end #respond_to
	  
    else
      respond_to do |format|
		format.js { render :nothing => true}
	  end #respond_to

    end #if
        
  end #def

private

  # ------------------------------------------------------------------------------------ #
  def find_attribute_quicky
    @attribute_quicky = AttributeQuicky.find(params[:attribute_quicky_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  # ------------------------------------------------------------------------------------ #
  def find_issue_by_id( id )
    @issue = Issue.find(id)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  # ------------------------------------------------------------------------------------ #
  def compile_attribute_list
  
	@attribute_list = []
    if @attribute_quicky.issue_id && @attribute_quicky.issue.present? && @attribute_quicky.issue.visible?(User.current)
      @issue = @attribute_quicky.issue
	  journals = @issue.journals.includes(:user, :details).
					  references(:user, :details).
					  reorder(:created_on, :id).to_a
	  journals.each_with_index {|j,i| j.indice = i+1}
	  journals.reject!(&:private_notes?) unless User.current.allowed_to?(:view_private_notes, @issue.project)
	  Journal.preload_journals_details_custom_fields(journals)
	  journals.select! {|journal| journal.notes? || journal.visible_details.any?}
 
	  journal = journals.last
	
	  if journal.present? && journal.details.any? 
	
		details = journal.visible_details.to_a
		details.select! {|detail| ['attr', 'cf'].include?(detail['property']) } 
		details.each do |detail|
		  @attribute_list << detail.attributes.except!('id')
		end
	  end #if
	end #if

  end #def
  
  # ------------------------------------------------------------------------------------ #
  def issue_attribute_list( issue )
  
	attribute_list = []
	journals = issue.
				journals.
				includes(:user, :details).
				references(:user, :details).
				reorder(:created_on, :id).to_a
				
	journals.each_with_index {|j,i| j.indice = i+1}
	journals.reject!(&:private_notes?) unless User.current.allowed_to?(:view_private_notes, issue.project)
	Journal.preload_journals_details_custom_fields(journals)
	journals.select! {|journal| journal.notes? || journal.visible_details.any?}

	journal = journals.last
  
	if journal.present? && journal.details.any? 
  
	  details = journal.visible_details.to_a
	  details.select! {|detail| ['attr', 'cf'].include?(detail['property']) } 
	  details.each do |detail|
		attribute_list << detail.attributes
	  end
	end #if
    attribute_list
  end #def
  
  
  # ------------------------------------------------------------------------------------ #
  def build_new_attribute_quicky_from_params
  
    @attribute_quicky = AttributeQuicky.new
    @attribute_quicky.project = @project
     new_time_entry
    
    if params.key?(:attribute_quicky)

app/helpers/attribute_quickies_helper.rb
# encoding: utf-8
#
# Redmine plugin for quick attribute setting of redmine issues
#
# Copyright © 2018 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module AttributeQuickiesHelper

  def detect_description_change( journal_details )

    journal_details.any? {|journal_detail| journal_detail.property == "attr" && journal_detail.prop_key == "description" }
  
  end #def

end #module

app/views/attribute_quickies/_form.html.erb
<%= labelled_fields_for :attribute_quicky, @attribute_quicky do |f| %>
<%= error_messages_for 'attribute_quicky' %>
<div class="splitcontent">  
  <div class="splitcontentleft">

	  <fieldset class="box tabular" id="attribute_quicky_name"><legend><%= l(:label_attribute_quicky_naming) %></legend>
		<p><%= f.text_field :name, :size => 30, :id => "attribute_quicky_name", :required => true %></p>
	  </fieldset>

	  <fieldset class="box tabular" id="attribute_quicky_description"><legend><%= l(:attribute_quickies_notice_description) %></legend>
		<p><%= f.text_area :description, :rows => 2, :id => "attribute_quicky_description", :required => true %></p>
	  </fieldset>

	  <fieldset class="box tabular" id="attribute_quicky_template"><legend><%=l(:text_copy_changed_attributes_from)%></legend>
		<p>
		  <%= f.text_field :issue_template_id, :size => 10, :id => "attribute_quicky_template_issue", :required => true %>
		  <%= f.hidden_field :project_id, :value => @project.id %>
		  <%= hidden_field_tag :tab, 'attribute_quickies' %>
		  <%= javascript_tag "observeAutocompleteField('attribute_quicky_template_issue', '#{auto_complete_issues_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')".html_safe %>
		  <%= link_to_function l(:button_copy), "attributeQuickiesForm('#{attribute_quickies_issue_attributes_path(@project)}', '#attribute_quicky-form')", :class => 'icon icon-copy' %>
		</p>
		<p><%= f.check_box :strict_match %></p>
		<div class="attribute_quicky_list" id="attribute_quicky_attribute_list">
		  <%= render 'issue_attributes_form'%>
		</div>
	  </fieldset>
	
	  <fieldset class="box tabular"><legend><%= l(:button_log_time) %></legend>
		<%= labelled_fields_for :time_entry, @time_entry do |time_entry| %>
		  <div class="splitcontent">
			<div class="splitcontentleft">
			  <p><%= time_entry.text_field :hours, :size => 6, :label => :label_spent_time %> <%= l(:field_hours) %></p>
			</div>
			<div class="splitcontentright">
			  <p><%= time_entry.select :activity_id, activity_collection_for_select_options %></p>
			</div>
		  </div>
		  <p><%= time_entry.text_field :comments, :size => 60 %></p>
		  <% @time_entry.custom_field_values.each do |value| %>
			<p><%= custom_field_tag_with_label :time_entry, value %></p>
		  <% end %>
		<% end %>
	  </fieldset>

	  <fieldset class="box tabular" id="attribute_quicky_assign_to_last_author"><legend><%= l(:label_attribute_quickies_assign_to_last_author) %></legend>
		<p><%= f.check_box :assign_to_last_author %></p>
	  </fieldset>

	  <fieldset class="box tabular" id="attribute_quicky_add_notes"><legend><%= l(:label_attribute_quickies_add_notes) %></legend>
		<p><%= f.check_box :add_notes, :onchange => "$('#form_attribute_quicky_notes').toggle(); return false;" %></p>
	  </fieldset>

  </div>
  
  <div class="splitcontentright">

	  <fieldset class="box tabular" id="atribute_quicky_role_ids"><legend><%=l(:field_visible)%></legend>
	  <p>
		<label class="block">
		  <%= radio_button_tag 'attribute_quicky[visibility]', 1, @attribute_quicky.visibility, :id => 'attribute_quicky_visible_on',
				:data => {:disables => '.attribute_quicky_role input'} %>
		  <%= l(:label_visibility_public) %>
		</label>
		<label class="block">
		  <%= radio_button_tag 'attribute_quicky[visibility]', 0, !@attribute_quicky.visibility, :id => 'attribute_quicky_visible_off',
				:data => {:enables => '.attribute_quicky_role input'} %>
		  <%= l(:label_visibility_roles) %>:
		</label>
		<% Role.givable.sorted.each do |role| %>
		  <label class="block attribute_quicky_role" style="padding-left:2em;">
			<%= check_box_tag 'attribute_quicky[role_ids][]', role.id, @attribute_quicky.roles.include?(role), :id => nil %>
			<%= role.name %>
		  </label>
		<% end %>
		<%= hidden_field_tag 'attribute_quicky[role_ids][]', '' %>
	  </p>
	  </fieldset>

	  <fieldset class="box" id="attribute_quicky_tracker_ids"><legend><%=l(:label_tracker_plural)%></legend>
		<p>
		  <% Tracker.sorted.each do |tracker| %>
			<%= check_box_tag "attribute_quicky[tracker_ids][]",
							  tracker.id,
							  (@attribute_quicky.trackers.include? tracker),
							  :id => "attribute_quicky_tracker_ids_#{tracker.id}" %>
			<label class="no-css" for="attribute_quicky_tracker_ids_<%=tracker.id%>">
			  <%= tracker.name %>
			</label>
		  <% end %>
		</p>
		<%= hidden_field_tag "attribute_quicky[tracker_ids][]", '' %>
		<p><%= check_all_links 'attribute_quicky_tracker_ids' %></p>
	  </fieldset>
	
	  <% if @attribute_quicky.attachments.any? %>
		<fieldset class="box tabular" id="attribute_quicky_attachments"><legend><%=l(:label_attachments)%></legend>
			<p>&nbsp;<%= link_to_attachments( @attribute_quicky, :thumbnails => true ) %>&nbsp;<!-- important - this fixes the collapse problem --></p>
		</fieldset>
	  <% end %>
	
  </div>
  
</div>

<div class="box filedroplistner" id="form_attribute_quicky_notes" <%= @attribute_quicky.add_notes ? "" : "style='display: none;'".html_safe  %> >
  <fieldset><legend><%= l(:field_notes) %></legend>
    <%= f.text_area :notes, :cols => 60, :rows => 10, :class => 'wiki-edit', :no_label => true %>
    <%= wikitoolbar_for 'attribute_quicky_notes' %>

    <% if @issue.safe_attribute? 'private_notes' %>
     <%= f.check_box :private_notes, :no_label => true %> <label for="attribute_quicky_private_notes"><%= l(:field_private_notes) %></label>
    <% end %>
    
    <span id="attribute_quicky_hook"><%= call_hook(:view_issues_edit_notes_bottom, { :issue => @issue, :notes => @notes, :form => f }) %></span>
  </fieldset>
  
  <fieldset><legend><%= l(:label_attachment_plural) %></legend>
    <p><%= render :partial => 'attachments/form', :locals => {:container => @issue} %></p>
  </fieldset>
  
</div>

<%= submit_tag l(:button_save) %>
<%= preview_link preview_attribute_quickies_notes_path(@project), 'attribute_quicky-form' %> |
<%= link_to l(:button_cancel), {}, :onclick => "$('#preview').empty(); return false;" %>

<div id="preview" class="wiki"></div>

<%- end %>
<% heads_for_wiki_formatter %>
<%= javascript_include_tag('attribute_quickies', plugin: 'redmine_attribute_quickies') %>

app/views/attribute_quickies/_index.html.erb
<div class="contextual">
  <%= link_to l(:label_settings),
                { controller: 'settings', action: 'plugin', id: 'redmine_attribute_quickies' },
                :class => 'attribute_quickies icon plugin' %>
</div>
<p>
<%= link_to l(:label_attribute_quicky_new),
			  new_attribute_quicky_path(@project, :tab => params[:tab]), 
			  :class => 'icon icon-add' %>
</p>
<% if AttributeQuicky.where(:project_id => @project.id).count == 0 %>
  <%= render partial: "attribute_quickies/nodata" %>
<% else %>
  <h3 class="attribute_quicky"><%= l(:label_attribute_quickies_edit) %></h3>
  <div class="attribute_quickies_box">
	<table class="list attribute_quickies">
	  <thead><tr>
	  <th><%=l(:label_attribute_quicky_id)%></th>
	  <th><%=l(:field_name)%></th>
	  <th><%=l(:field_description)%></th>
	  <th></th>
	  </tr></thead>
	  <tbody>
	  <% AttributeQuicky.where(:project_id => @project.id).order(:position).to_a.each do |attribute_quicky| %>
		<tr class="<%= cycle("odd", "even") %>">
		<td class="category"><%= link_to attribute_quicky.id, edit_attribute_quicky_path(@project, attribute_quicky) %></td>
		<td class="category"><%= link_to attribute_quicky.name, edit_attribute_quicky_path(@project, attribute_quicky) %></td>
		<td class="count"><%= link_to attribute_quicky.description, edit_attribute_quicky_path(@project, attribute_quicky) %></td>
		<td class="buttons">
		  <%= reorder_handle(attribute_quicky, :url => attribute_quicky_path(@project, attribute_quicky) ) %>
		  <%= delete_link attribute_quicky_path(@project, attribute_quicky, :tab => params[:tab]) %>
		</td>
		</tr>
	  <% end %>
	  </tbody>
	</table>
  </div>
<%- end %>
<% html_title(l(:label_redmine_attribute_quickies)) -%>

<%= javascript_tag do %>
  $(function() { $("table.attribute_quickies tbody").positionedItems(); });
<% end %>

app/views/attribute_quickies/_issue_attributes_form.html.erb
<%= fields_for :attribute_quicky do |f| %>
 <div class="attribute_quicky_list">
   <%- if @issue.present? %>
   <%- if @journal_details.any? %>
	 <div class="contextual">
	   <%- if detect_description_change( @journal_details ) %>
	     <label><%= l(:label_amended_description) %></label>
		 <%= f.select 'issue_description_action', options_for_select([[l(:label_append), 1], [l(:label_prepend), 2], [l(:label_replace), 3]], @attribute_quicky.issue_description_action ) %>
	   <%- else %>
		 <%= f.hidden_field 'issue_description_action', :value => 0 %>
	   <%- end %>
	 </div>
	 <%= details_to_strings(@journal_details).join("<br />\n").html_safe %>
   <%- else %>
	 <div class="flash warning"><%= l(:label_no_data) %></div>
	 <%= f.hidden_field 'issue_description_action', :value => 0 %>
   <%- end %>
   <%- else %>
	 <div class="flash error"><%= l(:error_message_issue_not_available) %></div>
	 <%= f.hidden_field 'issue_description_action', :value => 0 %>
   <%- end %>
 </div>
 <%= hidden_field_tag 'issue_id', @issue.id if @issue.present? %>
<%- end %>

app/views/attribute_quickies/_issue_attributes_form_hook.html.erb
<%= fields_for :attribute_quicky do |f| %>
<%= call_hook(:view_issues_edit_notes_bottom, { :issue => @issue, :notes => @notes, :form => f }) %>
<%- end #form_for %>

app/views/attribute_quickies/_nodata.html.erb
<p class="nodata"><%= l(:label_no_attribute_quickies_defined) %></p>

app/views/attribute_quickies/edit.html.erb
<h2><%= link_to l(:label_redmine_attribute_quickies), attribute_quickies_path %> » <%= l(:label_attribute_quicky_edit, :id => @attribute_quicky.id ) %></h2>
<%= form_for @attribute_quicky, {:url => attribute_quicky_path(@project, @attribute_quicky),
								 :method => :put,
								 :html => {:id => "attribute_quicky-form" }
								 } do |f| %>
<%= render :partial => 'form', :locals => {:f => f }  %>
<%- end #form_for %>

app/views/attribute_quickies/issue.html.erb
<% if @notes %>
  <fieldset class="preview"><legend><%= l(:field_notes) %></legend>
    <%= textilizable @notes, :attachments => @attachments, :object => @issue %>
  </fieldset>
<% end %>

app/views/attribute_quickies/issue_attributes.js.erb
$('#attribute_quicky_attribute_list').html('<%= escape_javascript @content.html_safe %>' );
$('#attribute_quicky_hook').html('<%= escape_javascript @hook_content.html_safe %>' );

app/views/attribute_quickies/new.html.erb
<h2><%= link_to l(:label_redmine_attribute_quickies), attribute_quickies_path %> » <%= l(:label_attribute_quicky_new) %></h2>
<%= form_for @attribute_quicky, {:url => attribute_quickies_path(@project),
								 :method => :post,
							     :html => {:id => "attribute_quicky-form" }
								 } do |f| %>
<%= render :partial => 'form', :locals => {:f => f }  %>
<%- end #form_for %>